# yaml-language-server: $schema=https://app.stainlessapi.com/config.schema.json

organization:
  name: mpesaflow
  docs: https://docs.mpesaflow.com
  contact: support@mpesaflow.com

targets:
  node:
    package_name: mpesaflow
    production_repo: MpesaFlow/mpesaflow-node
    publish:
      npm: true
  python:
    package_name: mpesaflow
    production_repo: MpesaFlow/mpesaflow-python
    publish:
      pypi: true
  java:
    reverse_domain: com.mpesaflow.api
    production_repo: MpesaFlow/mpesaflow-java
    publish:
      maven: true

client_settings:
  opts:
    app_api_key:
      type: string
      description: API key for application access
      nullable: true
      read_env: APP_API_KEY
      auth:
        security_scheme: AppApiKey
        role: value
    root_api_key:
      type: string
      description: API key for root access
      nullable: true
      read_env: ROOT_API_KEY
      auth:
        security_scheme: RootApiKey
        role: value

environments:
  production: https://api.mpesaflow.com
  sandbox: https://sandbox-api.mpesaflow.com

pagination:
  - name: cursor_id_pagination
    type: cursor_id
    request:
      starting_after:
        type: string
        x-stainless-pagination-property:
          purpose: next_cursor_id_param
      ending_before:
        type: string
        x-stainless-pagination-property:
          purpose: previous_cursor_id_param
      limit:
        type: integer
    response:
      data:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              x-stainless-pagination-property:
                purpose: cursor_item_id
          required:
            - id

resources:
  apps:
    models:
      application: Application
    methods:
      create: post /apps/create
      list:
        endpoint: get /apps/list
        paginated: CursorIDPage
      delete: delete /apps/{appId}
    subresources:
      api_keys:
        methods:
          create: post /apps/{appId}/api-keys/create
          list:
            endpoint: get /apps/{appId}/api-keys/list
            paginated: CursorIDPage
          delete: delete /apps/{appId}/api-keys/{apiKeyId}

  transactions:
    models:
      transaction: Transaction
    methods:
      create: post /transactions/create
      list:
        endpoint: get /transactions/list
        paginated: false
      retrieve: get /transactions/{transactionId}
      


settings:
  license: Apache-2.0

readme:
  example_requests:
    default:
      type: request
      endpoint: post /transactions/create
      params: &ref_0 {}
    headline:
      type: request
      endpoint: post /transactions/create
      params: *ref_0
    pagination:
      type: request
      endpoint: get /transactions/list
      params: {}